// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/music.tsx";
import * as $2 from "./routes/playlists.tsx";
import * as $$0 from "./islands/Config.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Menu.tsx";
import * as $$3 from "./islands/MenuButton.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/music.tsx": $1,
    "./routes/playlists.tsx": $2,
  },
  islands: {
    "./islands/Config.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Menu.tsx": $$2,
    "./islands/MenuButton.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
